language: csharp
script:
  - sudo ./build.sh --target=$TARGET --$SCRIPTARGS
os: osx
matrix:
  include:
    - dotnet: 2.1.502
      env: TARGET=TestCore SCRIPTARGS="netcore=\"netcoreapp2.1\""
    - dotnet: 3.1.201
      env: TARGET=TestCore SCRIPTARGS=
    - mono: latest
      env: TARGET=Test SCRIPTARGS=
git:
  submodules: false
cache:
  directories:
    - Source/packages